# Generated by Django 6.0.6 on 2026-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('quality', models.CharField(choices=[('360p', '360p'), ('720p', '720p'), ('1080p', '1080p')], max_length=5)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.FileField(upload_to='thumbnails/')),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
