# Generated by Django 6.0.6 on 2026-06-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoList',
            new_name='Video',
        ),
    ]
